import React from "react";
import "./TermsAndConditionPage.css";
const TermsAndConditionsPage = () => {
  return (
    <div className="privacypolicy">
      <div className="pvheader">Terms of Use</div>
      <div className="introduction">
        <span className="ihead">
          A. Terms Of Use For Information Dissemination:
        </span>
        <span>
          1. This document is an electronic record in terms of the amended
          Information Technology Act, 2000 and rules and regulations made
          thereunder. This electronic record is generated by a computer system
          and does not require any physical or digital signatures. This document
          is published in accordance with the provisions of Rule 3 (1) of the
          Information Technology (Intermediaries Guidelines) Rules, 2011 that
          require publishing the Terms for access or usage of vendorlist service
          via vendorlist Portal. This document meets the stipulations and
          conditions mentioned in Section 65B (2) of the Indian Evidence Act,
          1872..
          <br />
          <br />
          2. We may periodically change the Terms and the Site without notice,
          and you are responsible for checking these Terms periodically for
          revisions. All amended Terms become effective upon our posting to the
          Site, and any use of the site after such revisions have been posted
          signifies your consent to the changes..
          <br />
          <br /> We use a diverse range of information, text, photographs,
          designs, graphics, images, sound and video recordings, animation,
          content, advertisement, and other materials and effects (collectively
          “Materials”) for the search services on the Platforms. We provide the
          Material through the Platforms FOR YOUR PERSONAL AND NON-COMMERCIAL
          USE ONLY.
        </span>
      </div>
      <div className="introduction">
        <span className="ihead">B. How you may use our materials:</span>
        <span>
          1. We use a diverse range of information, text, photographs, designs,
          graphics, images, sound and video recordings, animation, content,
          advertisement, and other materials and effects (collectively
          “Materials”) for the search services on the Platforms. We provide the
          Material through the Platforms FOR YOUR PERSONAL AND NON-COMMERCIAL
          USE ONLY.
          <br />
          <br />
          2. While every attempt has been made to ascertain the authenticity of
          the Platforms content, Vendorlist is not liable for any kind of
          damages, losses or action arising directly or indirectly, due to
          access and/or use of the content in the Platforms including but not
          limited to decisions based on the content in the Platforms which
          results in any loss of data, revenue, profits, property, infection by
          viruses, etc.
          <br />
          <br /> 3.Accordingly, you may view, use, copy, and distribute the
          Materials found on the Platforms for internal, non-commercial,
          informational purposes only. You are prohibited from data mining,
          scraping, crawling, or using any process or processes that send
          automated queries to Vendorlist. You may not use the Platforms or any
          of them to compile a collection of listings, including a competing
          listing product or service. You may not use the Platforms or any
          Materials for any unsolicited commercial e-mail. Except as authorized
          in this paragraph, you are not being granted a license under any
          copyright, trademark, patent, or other intellectual property right in
          the Materials or the products, services, processes, or technology
          described therein. All such rights are retained by Vendorlist, its
          subsidiaries, parent companies, and/or any third-party owner of such
          rights.
        </span>
      </div>
      <div className="introduction">
        <span className="ihead">C. How You May Use Our Marks:</span>
        <span>
          1. The Vendorlist company names and logos and all related products and
          service names, design marks, and slogans are trademarks and service
          marks owned by and used under license from Vendorlist or its wholly
          owned subsidiaries. All other trademarks and service marks herein are
          the property of their respective owners. All copies that you make of
          the Materials on any of the Platforms must bear any copyright,
          trademark, or other proprietary notice located on the respective
          Platforms that pertains to the material being copied. You are not
          authorized to use any Vendorlist name or mark in any advertising,
          publicity, or in any other commercial manner without the prior written
          consent of Vendorlist. Requests for authorization should be made to
          infovendorlist@gmail.com
          <br />
          <br />
          2. This Privacy Policy is an electronic agreement formed under the
          Information Technology Act, 2000 and the rules and regulations made
          there under (as amended till date) including the Information
          Technology (Reasonable security practices and procedures and sensitive
          personal data or information) Rules, 2011 & the Information Technology
          (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021.
          It does not require any physical or digital signatures to make the
          terms of this policy binding.
          <br />
          <br />
        </span>
      </div>
      <div className="introduction">
        <span className="ihead">D. Cookies:</span>
        <span>
          1. We employ the use of cookies. By accessing Dekho Market , you
          agreed to use cookies in agreement with the Dekho Market's Privacy
          Policy
          <br />
          <br />
          2. Most interactive websites use cookies to let us retrieve the user's
          details for each visit. Cookies are used by our website to enable the
          functionality of certain areas to make it easier for people visiting
          our website. Some of our affiliate/advertising partners may also use
          cookies.
          <br />
          <br />
        </span>
      </div>
      <div className="introduction">
        <span className="ihead">E. License:</span>
        <span>
          1. Unless otherwise stated, Dekho Market and/or its licensors own the
          intellectual property rights for all material on Dekho Market . All
          intellectual property rights are reserved. You may access this from
          Dekho Market for your own personal use subjected to restrictions set
          in these terms and conditions..
          <br />
          <br />
          2. Republish material from Dekho Market Sell, rent or sub-license
          material from Dekho Market Reproduce, duplicate or copy material from
          Dekho Market Redistribute content from Dekho Market This Agreement
          shall begin on the date hereof. Our Terms and Conditions were created
          with the help of the Free Terms and Conditions Generator.
          <br />
          <br /> 3.Parts of this website offer an opportunity for users to post
          and exchange opinions and information in certain areas of the website.
          Dekho Market does not filter, edit, publish or review Comments prior
          to their presence on the website. Comments do not reflect the views
          and opinions of Dekho Market,its agents and/or affiliates. Comments
          reflect the views and opinions of the person who post their views and
          opinions. To the extent permitted by applicable laws, Dekho Market
          shall not be liable for the Comments or for any liability, damages or
          expenses caused and/or suffered as a result of any use of and/or
          posting of and/or appearance of the Comments on this website..
        </span>
      </div>
      <div className="introduction">
        <span className="ihead">F. Reservation of Rights:</span>
        <span>
          1. We reserve the right to request that you remove all links or any
          particular link to our Website. You approve to immediately remove all
          links to our Website upon request. We also reserve the right to amen
          these terms and conditions and it's linking policy at any time. By
          continuously linking to our Website, you agree to be bound to and
          follow these linking terms and conditions
          <br />
          <br />
          2. If you find any link on our Website that is offensive for any
          reason, you are free to contact and inform us any moment. We will
          consider requests to remove links but we are not obligated to or so or
          to respond to you directly.
          <br />
          <br /> 3.We do not ensure that the information on this website is
          correct, we do not warrant its completeness or accuracy; nor do we
          promise to ensure that the website remains available or that the
          material on the website is kept up to date.
        </span>
      </div>
      <div className="introduction">
        <span className="ihead">G. Disclaimer:</span>
        <span>
          1. To the maximum extent permitted by applicable law, we exclude all
          representations, warranties and conditions relating to our website and
          the use of this website. Nothing in this disclaimer will: <br />
          limit or exclude our or your liability for death or personal injury;
          limit or exclude our or your liability for fraud or fraudulent
          misrepresentation; limit any of our or your liabilities in any way
          that is not permitted under applicable law; or exclude any of our or
          your liabilities that may not be excluded under applicable law. The
          limitations and prohibitions of liability set in this Section and
          elsewhere in this disclaimer: (a) are subject to the preceding
          paragraph; and (b) govern all liabilities arising under the
          disclaimer, including liabilities arising in contract, in tort and for
          breach of statutory duty.
          <br />
          <br />
        </span>
      </div>
    </div>
  );
};

export default TermsAndConditionsPage;
